// Mocks generated by Mockito 5.4.6 from annotations
// in c3_offline/test/presentation/home/home_viewModel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:c3_offline/api/client/api_result.dart' as _i4;
import 'package:c3_offline/domain/model/category.dart' as _i5;
import 'package:c3_offline/domain/model/product.dart' as _i8;
import 'package:c3_offline/domain/usecase/GetCategoriesUseCase.dart' as _i2;
import 'package:c3_offline/domain/usecase/GetMostSellingProducts.dart' as _i10;
import 'package:c3_offline/domain/usecase/GetNewArrivalProducts.dart' as _i9;
import 'package:c3_offline/domain/usecase/GetProductsByCategoryId.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GetCategoriesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCategoriesUseCase extends _i1.Mock
    implements _i2.GetCategoriesUseCase {
  MockGetCategoriesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i5.Category>>> invoke({
    int? limit = 10,
    int? page = 1,
    String? keyword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#invoke, [], {
              #limit: limit,
              #page: page,
              #keyword: keyword,
            }),
            returnValue: _i3.Future<_i4.Result<List<_i5.Category>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.Category>>>(
                this,
                Invocation.method(#invoke, [], {
                  #limit: limit,
                  #page: page,
                  #keyword: keyword,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.Category>>>);
}

/// A class which mocks [GetProductsByCategoryIdUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProductsByCategoryIdUseCase extends _i1.Mock
    implements _i7.GetProductsByCategoryIdUseCase {
  MockGetProductsByCategoryIdUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i8.Product>>> invoke({
    int? limit = 10,
    int? page = 1,
    String? categoryId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#invoke, [], {
              #limit: limit,
              #page: page,
              #categoryId: categoryId,
            }),
            returnValue: _i3.Future<_i4.Result<List<_i8.Product>>>.value(
              _i6.dummyValue<_i4.Result<List<_i8.Product>>>(
                this,
                Invocation.method(#invoke, [], {
                  #limit: limit,
                  #page: page,
                  #categoryId: categoryId,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i8.Product>>>);
}

/// A class which mocks [GetNewArrivalsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetNewArrivalsUseCase extends _i1.Mock
    implements _i9.GetNewArrivalsUseCase {
  MockGetNewArrivalsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i8.Product>>> invoke({
    int? limit = 10,
    int? page = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#invoke, [], {#limit: limit, #page: page}),
            returnValue: _i3.Future<_i4.Result<List<_i8.Product>>>.value(
              _i6.dummyValue<_i4.Result<List<_i8.Product>>>(
                this,
                Invocation.method(#invoke, [], {#limit: limit, #page: page}),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i8.Product>>>);
}

/// A class which mocks [GetMostSellingProducts].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMostSellingProducts extends _i1.Mock
    implements _i10.GetMostSellingProducts {
  MockGetMostSellingProducts() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i8.Product>>> invoke({
    int? limit = 10,
    int? page = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#invoke, [], {#limit: limit, #page: page}),
            returnValue: _i3.Future<_i4.Result<List<_i8.Product>>>.value(
              _i6.dummyValue<_i4.Result<List<_i8.Product>>>(
                this,
                Invocation.method(#invoke, [], {#limit: limit, #page: page}),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i8.Product>>>);
}
