// Mocks generated by Mockito 5.4.6 from annotations
// in c3_offline/test/data/repositories/BrandsRepoImpl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:c3_offline/api/client/api_result.dart' as _i4;
import 'package:c3_offline/data/dataSource/BrandsRemoteDataSource.dart' as _i2;
import 'package:c3_offline/domain/model/brand.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [BrandsRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockBrandsRemoteDataSource extends _i1.Mock
    implements _i2.BrandsRemoteDataSource {
  MockBrandsRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i5.Brand>>> getBrands({
    int? limit = 10,
    int? page = 1,
    String? keyword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getBrands, [], {
              #limit: limit,
              #page: page,
              #keyword: keyword,
            }),
            returnValue: _i3.Future<_i4.Result<List<_i5.Brand>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.Brand>>>(
                this,
                Invocation.method(#getBrands, [], {
                  #limit: limit,
                  #page: page,
                  #keyword: keyword,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.Brand>>>);
}
