// Mocks generated by Mockito 5.4.6 from annotations
// in c3_offline/test/api/dataSource/BrandsRemoteDataSourceImpl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:c3_offline/api/client/ApiClient.dart' as _i5;
import 'package:c3_offline/api/response/brands_response.dart' as _i3;
import 'package:c3_offline/api/response/categories_response.dart' as _i4;
import 'package:c3_offline/api/response/products_response.dart' as _i2;
import 'package:c3_offline/domain/model/SortFields.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProductsResponse_0 extends _i1.SmartFake
    implements _i2.ProductsResponse {
  _FakeProductsResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBrandsResponse_1 extends _i1.SmartFake
    implements _i3.BrandsResponse {
  _FakeBrandsResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCategoriesResponse_2 extends _i1.SmartFake
    implements _i4.CategoriesResponse {
  _FakeCategoriesResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i5.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.ProductsResponse> getProducts({
    int? limit = 10,
    int? page = 1,
    String? keyword,
    List<String>? categories,
    _i7.SortFields? sortField,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProducts, [], {
              #limit: limit,
              #page: page,
              #keyword: keyword,
              #categories: categories,
              #sortField: sortField,
            }),
            returnValue: _i6.Future<_i2.ProductsResponse>.value(
              _FakeProductsResponse_0(
                this,
                Invocation.method(#getProducts, [], {
                  #limit: limit,
                  #page: page,
                  #keyword: keyword,
                  #categories: categories,
                  #sortField: sortField,
                }),
              ),
            ),
          )
          as _i6.Future<_i2.ProductsResponse>);

  @override
  _i6.Future<_i3.BrandsResponse> getBrands({
    int? limit = 10,
    int? page = 1,
    String? keyword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getBrands, [], {
              #limit: limit,
              #page: page,
              #keyword: keyword,
            }),
            returnValue: _i6.Future<_i3.BrandsResponse>.value(
              _FakeBrandsResponse_1(
                this,
                Invocation.method(#getBrands, [], {
                  #limit: limit,
                  #page: page,
                  #keyword: keyword,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.BrandsResponse>);

  @override
  _i6.Future<_i4.CategoriesResponse> getCategories({
    int? limit = 10,
    int? page = 1,
    String? keyword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, [], {
              #limit: limit,
              #page: page,
              #keyword: keyword,
            }),
            returnValue: _i6.Future<_i4.CategoriesResponse>.value(
              _FakeCategoriesResponse_2(
                this,
                Invocation.method(#getCategories, [], {
                  #limit: limit,
                  #page: page,
                  #keyword: keyword,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.CategoriesResponse>);
}
