// Mocks generated by Mockito 5.4.6 from annotations
// in c3_offline/test/domain/usecase/GetMostSellingProducts_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:c3_offline/api/client/api_result.dart' as _i4;
import 'package:c3_offline/domain/model/product.dart' as _i5;
import 'package:c3_offline/domain/model/SortFields.dart' as _i6;
import 'package:c3_offline/domain/respositories/ProductsRepo.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ProductsRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductsRepo extends _i1.Mock implements _i2.ProductsRepo {
  MockProductsRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i5.Product>>> getProducts({
    int? limit = 10,
    int? page = 1,
    String? keyword,
    List<String>? categories,
    _i6.SortFields? sortField,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getProducts, [], {
              #limit: limit,
              #page: page,
              #keyword: keyword,
              #categories: categories,
              #sortField: sortField,
            }),
            returnValue: _i3.Future<_i4.Result<List<_i5.Product>>>.value(
              _i7.dummyValue<_i4.Result<List<_i5.Product>>>(
                this,
                Invocation.method(#getProducts, [], {
                  #limit: limit,
                  #page: page,
                  #keyword: keyword,
                  #categories: categories,
                  #sortField: sortField,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.Product>>>);
}
